curl 'http://localhost:3011/api/v1/concepts/search/LOINC/CBC' \
  -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1OWFkNTMwMi1iYzQ1LTQ0M2ItYTkwYi0yMTU5NjlmMGM0ZTQiLCJvcmdhbml6YXRpb25JZCI6ImRmM2I0YWZkLTk5NTUtNDYxNy05YTgyLTI2NGNjNzNkZDhiMiIsInVzZXJuYW1lIjoiYWRtaW4iLCJyb2xlcyI6WyJhZG1pbiJdLCJwZXJtaXNzaW9ucyI6W10sImlhdCI6MTc3NzU0Mzc2OSwiZXhwIjoxNzc3NTQ0NjY5fQ.x-vhLivPy8hjmo7ZgLequMjCBb3aYH9VCINSa9NXiGY' 
  