export enum CodingConcept {
  DICOM = 'DICOM',
  LOINC = 'LOINC',
  SNOMED = 'SNOMED',
  EMDEx = 'EMDEx',
  ICD10 = 'ICD10',
  RxNorm = 'RxNorm',

  STATE = 'STATE',
  LGA = 'LGA',
  WARD = 'WARD',
  FACILITY_TYPE = 'FACILITY_TYPE',
  FACILITY_LEVEL = 'FACILITY_LEVEL',
  OWNERSHIP_TYPE = 'OWNERSHIP_TYPE',
  OPERATIONAL_STATUS = 'OPERATIONAL_STATUS',
  REGISTRATION_STATUS = 'REGISTRATION_STATUS',
  LICENSE_STATUS = 'LICENSE_STATUS',
}
